# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://shortcasts.netlify.com'
baseurl: ''
title: 'ShortCasts'
description: 'Your iOS Shortcuts Podcast'
permalink: pretty
logo: "/assets/img/logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/
  Episodes: /episodes/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
  
  episodes:
    title: Episodes
    output: true

defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
  